#-------------------------------------------------
# $Id: pcalc.pri 1352 2011-01-26 22:01:25Z rutger $
# Project created 2015-02-25
# - for building calculations in PCALC
# - ../src path is required to use .pri file also from ../test
# ----------------------------------------------------------

FORMS += \
    ../src/gui/pcalc_classgeneratorwidget.ui \
    ../src/gui/pcalc_en1591selectgasketwidget.ui \
    ../src/gui/pcalc_en1591widget.ui \
    ../src/gui/rb_databasetablewidget.ui \
    ../src/gui/std_dimensionwidget.ui \
    ../src/gui/std_matcreepwidget.ui \
    ../src/gui/std_matelasmodulwidget.ui \
    ../src/gui/std_materialwidget.ui \
    ../src/gui/std_matthermexpwidget.ui \
    ../src/gui/std_selectcomponentwidget.ui \
    ../src/gui/std_selectmaterialwidget.ui

HEADERS += \
    ../../peng/src/model/peng_project.h \
    ../src/actions/pcalc_actionclose.h \
    ../src/actions/pcalc_actiondimension.h \
    ../src/actions/pcalc_actioneditproject.h \
    ../src/actions/pcalc_actionen1591flange.h \
    ../src/actions/pcalc_actionengasket.h \
    ../src/actions/pcalc_actionfactory.h \
    ../src/actions/pcalc_actionmatcreep.h \
    ../src/actions/pcalc_actionmaterial.h \
    ../src/actions/pcalc_actionmatelasmodul.h \
    ../src/actions/pcalc_actionmatthermexp.h \
    ../src/actions/pcalc_actionplugin.h \
    ../src/actions/pcalc_actionselectproject.h \
    ../src/calc/en1591handler.h \
    ../src/calc/EN1591/assembly.h \
    ../src/calc/EN1591/bolt.h \
    ../src/calc/EN1591/calculator.h \
    ../src/calc/EN1591/flange.h \
    ../src/calc/EN1591/flange_blind.h \
    ../src/calc/EN1591/flange_integral.h \
    ../src/calc/EN1591/flange_loose.h \
    ../src/calc/EN1591/force.h \
    ../src/calc/EN1591/gasket.h \
    ../src/calc/EN1591/loadcase.h \
    ../src/calc/EN1591/loadcaselist.h \
    ../src/calc/EN1591/shell.h \
    ../src/calc/EN1591/washer.h \
    ../src/calc/EN1591/unittest/assemblytest.h \
    ../src/calc/EN1591/unittest/bolttest.h \
    ../src/calc/EN1591/unittest/flange_blindtest.h \
    ../src/calc/EN1591/unittest/flange_integraltest.h \
    ../src/calc/EN1591/unittest/flange_loosetest.h \
    ../src/calc/EN1591/unittest/flangetest.h \
    ../src/calc/EN1591/unittest/forcetest.h \
    ../src/calc/EN1591/unittest/gaskettest.h \
    ../src/calc/EN1591/unittest/washertest.h \
    ../src/calc/pcalc_inputoutput.h \
    ../src/calc/rb_allowanceservice.h \
    ../src/calc/rb_materialservice.h \
    ../src/calc/rb_namespace.h \
    ../src/calc/rb_qualityservice.h \
    ../src/calc/unittest/rb_tablemathtest.h \
    ../src/calc/unittest/rb_unittest.h \
    ../src/calc/unittest/rb_unittestfactory.h \
    ../src/calc/unittest/en1591_unittestfactory.h \
    ../src/gui/pcalc_classgeneratorwidget.h \
    ../src/gui/pcalc_dialogfactory.h \
    ../src/gui/pcalc_en13555gasketwidget.h \
    ../src/gui/pcalc_en13555manufwidget.h \
    ../src/gui/pcalc_en13555typewidget.h \
    ../src/gui/pcalc_en1591selectgasketwidget.h \
    ../src/gui/pcalc_en1591widget.h \
    ../src/gui/pcalc_projectdialog.h \
    ../src/gui/pcalc_projecteditwidget.h \
    ../src/gui/rb_databasetablewidget.h \
    ../src/gui/std_dimensiontablehelper.h \
    ../src/gui/std_dimensionwidget.h \
    ../src/gui/std_matcreepwidget.h \
    ../src/gui/std_matelasmodulwidget.h \
    ../src/gui/std_materialwidget.h \
    ../src/gui/std_matthermexpwidget.h \
    ../src/gui/std_selectcomponentwidget.h \
    ../src/gui/std_selectflangewidget.h \
    ../src/gui/std_selectmaterialwidget.h \
    ../src/model/EN1591/pcalc_en1591_assembly.h \
    ../src/model/EN1591/pcalc_en1591_boltnutwasher.h \
    ../src/model/EN1591/pcalc_en1591_flange.h \
    ../src/model/EN1591/pcalc_en1591_gasket.h \
    ../src/model/EN1591/pcalc_en1591_loadcase.h \
    ../src/model/EN1591/pcalc_en1591_shell.h \
    ../src/model/EN1591/std_en13555egeg.h \
    ../src/model/EN1591/std_en13555gasket.h \
    ../src/model/EN1591/std_en13555manufacturer.h \
    ../src/model/EN1591/std_en13555pqrdeltaegc.h \
    ../src/model/EN1591/std_en13555qsmaxalphag.h \
    ../src/model/EN1591/std_en13555qminl.h \
    ../src/model/EN1591/std_en13555qsminl.h \
    ../src/model/pcalc.h \
    ../src/model/pcalc_classgenerator.h \
    ../src/model/pcalc_generatorformula.h \
    ../src/model/pcalc_modelfactory.h \
    ../src/model/pcalc_objectfactory.h \
    ../src/model/std.h \
    ../src/model/std_creeptable.h \
    ../src/model/std_dimension.h \
    ../src/model/std_elasmodul.h \
    ../src/model/std_elasmodultable.h \
    ../src/model/std_extpresstable.h \
    ../src/model/std_flange.h \
    ../src/model/std_flangeasme.h \
    ../src/model/std_flangefacingdim.h \
    ../src/model/std_flangefacingdimasme.h \
    ../src/model/std_flangefacingtype.h \
    ../src/model/std_flangetype.h \
    ../src/model/std_flangetypelimit.h \
    ../src/model/std_material.h \
    ../src/model/std_rating.h \
    ../src/model/std_rmmin.h \
    ../src/model/std_rp02.h \
    ../src/model/std_rp10.h \
    ../src/model/std_rp10t10kh.h \
    ../src/model/std_rp10t100kh.h \
    ../src/model/std_rpt10kh.h \
    ../src/model/std_rpt100kh.h \
    ../src/model/std_rpt200kh.h \
    ../src/model/std_thermexp.h \
    ../src/model/std_thermexptable.h \
    ../src/utils/EN1591/en13445tableg.h \
    ../src/utils/EN1591/en13555property.h \
    ../src/utils/unittest/std_enmaterialhandlertest.h \
    ../src/utils/unittest/std_unittestfactory.h \
    ../src/utils/pcalc_report.h \
    ../src/utils/pcalc_sqlcommonfunctions.h \
    ../src/utils/pcalc_utilityfactory.h \
    ../src/utils/rb_tablemath.h \
    ../src/utils/std_enmaterialhandler.h \
    ../src/utils/std_materialhandler.h \
    ../src/utils/std_materialutility.h


SOURCES += \
    ../../peng/src/model/peng_project.cpp \
    ../src/actions/pcalc_actionclose.cpp \
    ../src/actions/pcalc_actiondimension.cpp \
    ../src/actions/pcalc_actioneditproject.cpp \
    ../src/actions/pcalc_actionen1591flange.cpp \
    ../src/actions/pcalc_actionengasket.cpp \
    ../src/actions/pcalc_actionfactory.cpp \
    ../src/actions/pcalc_actionmatcreep.cpp \
    ../src/actions/pcalc_actionmaterial.cpp \
    ../src/actions/pcalc_actionmatelasmodul.cpp \
    ../src/actions/pcalc_actionmatthermexp.cpp \
    ../src/actions/pcalc_actionplugin.cpp \
    ../src/actions/pcalc_actionselectproject.cpp \
    ../src/calc/en1591handler.cpp \
    ../src/calc/EN1591/assembly.cpp \
    ../src/calc/EN1591/bolt.cpp \
    ../src/calc/EN1591/calculator.cpp \
    ../src/calc/EN1591/flange.cpp \
    ../src/calc/EN1591/flange_blind.cpp \
    ../src/calc/EN1591/flange_integral.cpp \
    ../src/calc/EN1591/flange_loose.cpp \
    ../src/calc/EN1591/force.cpp \
    ../src/calc/EN1591/gasket.cpp \
    ../src/calc/EN1591/loadcase.cpp \
    ../src/calc/EN1591/loadcaselist.cpp \
    ../src/calc/EN1591/shell.cpp \
    ../src/calc/EN1591/washer.cpp \
    ../src/calc/EN1591/unittest/assemblytest.cpp \
    ../src/calc/EN1591/unittest/bolttest.cpp \
    ../src/calc/EN1591/unittest/flange_blindtest.cpp \
    ../src/calc/EN1591/unittest/flange_integraltest.cpp \
    ../src/calc/EN1591/unittest/flange_loosetest.cpp \
    ../src/calc/EN1591/unittest/flangetest.cpp \
    ../src/calc/EN1591/unittest/forcetest.cpp \
    ../src/calc/EN1591/unittest/gaskettest.cpp \
    ../src/calc/EN1591/unittest/washertest.cpp \
    ../src/calc/pcalc_inputoutput.cpp \
    ../src/calc/rb_allowanceservice.cpp \
    ../src/calc/rb_materialservice.cpp \
    ../src/calc/rb_qualityservice.cpp \
    ../src/calc/unittest/rb_tablemathtest.cpp \
    ../src/calc/unittest/rb_unittest.cpp \
    ../src/calc/unittest/rb_unittestfactory.cpp \
    ../src/calc/unittest/en1591_unittestfactory.cpp \
    ../src/gui/pcalc_classgeneratorwidget.cpp \
    ../src/gui/pcalc_dialogfactory.cpp \
    ../src/gui/pcalc_en13555gasketwidget.cpp \
    ../src/gui/pcalc_en13555manufwidget.cpp \
    ../src/gui/pcalc_en13555typewidget.cpp \
    ../src/gui/pcalc_en1591selectgasketwidget.cpp \
    ../src/gui/pcalc_en1591widget.cpp \
    ../src/gui/pcalc_projecteditwidget.cpp \
    ../src/gui/rb_databasetablewidget.cpp \
    ../src/gui/std_dimensiontablehelper.cpp \
    ../src/gui/std_dimensionwidget.cpp \
    ../src/gui/std_matcreepwidget.cpp \
    ../src/gui/std_matelasmodulwidget.cpp \
    ../src/gui/std_materialwidget.cpp \
    ../src/gui/std_matthermexpwidget.cpp \
    ../src/gui/std_selectcomponentwidget.cpp \
    ../src/gui/std_selectflangewidget.cpp \
    ../src/gui/std_selectmaterialwidget.cpp \
    ../src/model/EN1591/pcalc_en1591_assembly.cpp \
    ../src/model/EN1591/pcalc_en1591_boltnutwasher.cpp \
    ../src/model/EN1591/pcalc_en1591_flange.cpp \
    ../src/model/EN1591/pcalc_en1591_gasket.cpp \
    ../src/model/EN1591/pcalc_en1591_loadcase.cpp \
    ../src/model/EN1591/pcalc_en1591_shell.cpp \
    ../src/model/EN1591/std_en13555egeg.cpp \
    ../src/model/EN1591/std_en13555gasket.cpp \
    ../src/model/EN1591/std_en13555manufacturer.cpp \
    ../src/model/EN1591/std_en13555pqrdeltaegc.cpp \
    ../src/model/EN1591/std_en13555qminl.cpp \
    ../src/model/EN1591/std_en13555qsmaxalphag.cpp \
    ../src/model/EN1591/std_en13555qsminl.cpp \
    ../src/model/pcalc_classgenerator.cpp \
    ../src/model/pcalc_generatorformula.cpp \
    ../src/model/pcalc_modelfactory.cpp \
    ../src/model/pcalc_objectfactory.cpp \
    ../src/model/std_creeptable.cpp \
    ../src/model/std_dimension.cpp \
    ../src/model/std_elasmodul.cpp \
    ../src/model/std_elasmodultable.cpp \
    ../src/model/std_extpresstable.cpp \
    ../src/model/std_flange.cpp \
    ../src/model/std_flangeasme.cpp \
    ../src/model/std_flangefacingdim.cpp \
    ../src/model/std_flangefacingdimasme.cpp \
    ../src/model/std_flangefacingtype.cpp \
    ../src/model/std_flangetype.cpp \
    ../src/model/std_flangetypelimit.cpp \
    ../src/model/std_material.cpp \
    ../src/model/std_rating.cpp \
    ../src/model/std_rmmin.cpp \
    ../src/model/std_rp02.cpp \
    ../src/model/std_rp10.cpp \
    ../src/model/std_rp10t10kh.cpp \
    ../src/model/std_rp10t100kh.cpp \
    ../src/model/std_rpt10kh.cpp \
    ../src/model/std_rpt100kh.cpp \
    ../src/model/std_rpt200kh.cpp \
    ../src/model/std_thermexp.cpp \
    ../src/model/std_thermexptable.cpp \
    ../src/utils/EN1591/en13445tableg.cpp \
    ../src/utils/EN1591/en13555property.cpp \
    ../src/utils/unittest/std_enmaterialhandlertest.cpp \
    ../src/utils/unittest/std_unittestfactory.cpp \
    ../src/utils/pcalc_report.cpp \
    ../src/utils/pcalc_sqlcommonfunctions.cpp \
    ../src/utils/pcalc_utilityfactory.cpp \
    ../src/utils/rb_tablemath.cpp \
    ../src/utils/std_enmaterialhandler.cpp \
    ../src/utils/std_materialutility.cpp

RESOURCES += \
    ../../db/src/gui/db.qrc \
    ../src/gui/pcalc.qrc

OTHER_FILES += \
    ../src/actions/pcalc_actionplugin.json \
    ../src/gui/pcalc_en1591widget.dox
#    ../src/gui/std_selectmaterialwidget.dox
