# ----------------------------------------------------------
# $Id: db.pri 2248 2015-06-21 09:13:00Z rutger $
# Created: Nov 22, 2009 11:34:42 AM - rutger
#
# Copyright (C) 2009 Red-Bag. All rights reserved.
# This file is part of the Biluna DB project.
#
# See http://www.red-bag.com for further details.
#
# Comments:
# - form, header and sources listing
# - ../src path is required to use .pri file also from ../test
# ----------------------------------------------------------

# Biluna db_global.h for dynamic library
HEADERS = \
    ../src/utils/db_global.h \

# dxflib
HEADERS = \
    ../../thrd/qcad2/dxflib/src/dl_attributes.h\
    ../../thrd/qcad2/dxflib/src/dl_codes.h\
    ../../thrd/qcad2/dxflib/src/dl_creationadapter.h\
    ../../thrd/qcad2/dxflib/src/dl_creationinterface.h\
    ../../thrd/qcad2/dxflib/src/dl_dxf.h\
    ../../thrd/qcad2/dxflib/src/dl_entities.h\
    ../../thrd/qcad2/dxflib/src/dl_exception.h\
    ../../thrd/qcad2/dxflib/src/dl_extrusion.h\
    ../../thrd/qcad2/dxflib/src/dl_writer.h\
    ../../thrd/qcad2/dxflib/src/dl_writer_ascii.h

SOURCES = \
    ../../thrd/qcad2/dxflib/src/dl_dxf.cpp\
    ../../thrd/qcad2/dxflib/src/dl_writer_ascii.cpp

# fparser
HEADERS = \
    ../../thrd/qcad2/fparser/src/fparser.h
	
SOURCES = \
    ../../thrd/qcad2/fparser/src/fparser.cpp

# qcadactions
HEADERS = \
    ../../thrd/qcad2/qcadactions//src/blocks/rs_actionblocksadd.h \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblocksattributes.h \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblockscreate.h \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblocksedit.h \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblockseditinsert.h \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblocksinsert.h \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblocksremove.h \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblockstoggleview.h \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblocksshowall.h \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblockshideall.h \
    ../../thrd/qcad2/qcadactions/src/debugging/rs_actiondebugentities.h \
    ../../thrd/qcad2/qcadactions/src/debugging/rs_actiondebugguiactions.h \
    ../../thrd/qcad2/qcadactions/src/debugging/rs_actiondebugresize.h \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimaligned.h \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimangular.h \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimdiametric.h \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimension.h \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimleader.h \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimlinear.h \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimradial.h \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimordinate.h \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimhorizontal.h \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimvertical.h \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiontoolregeneratedimensions.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawarc3p.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawarc.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawarctangential.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawcircle2p.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawcircle3p.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawcirclecr.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawcircle.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawellipsearcaxis.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawellipseaxis.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawhatch.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawimage.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlineangle.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinebisector.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinefree.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawline.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinehorizontal.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinehorvert.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlineparallel.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawarcparallel.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawcircleparallel.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlineparallelthrough.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinepolygon2.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinepolygon.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinerectangle.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinerelangle.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinetangent1.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinetangent2.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinevertical.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlineorthogonal.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawpoint.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawpolyline.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawspline.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawtext.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actionpolylineadd.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actionpolylineappend.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actionpolylinedel.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actionpolylinedelbetween.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actionpolylineequidistant.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actionpolylinefromsegments.h \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actionpolylinetrim.h \
    ../../thrd/qcad2/qcadactions/src/edit/rs_actioneditcopy.h \
    ../../thrd/qcad2/qcadactions/src/edit/rs_actioneditcopyautoref.h \
    ../../thrd/qcad2/qcadactions/src/edit/rs_actioneditcut.h \
    ../../thrd/qcad2/qcadactions/src/edit/rs_actioneditcutautoref.h \
    ../../thrd/qcad2/qcadactions/src/edit/rs_actioneditpaste.h \
    ../../thrd/qcad2/qcadactions/src/edit/rs_actioneditundo.h \
    ../../thrd/qcad2/qcadactions/src/edit/rs_actioneditredo.h \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfileclose.h \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfileexport.h \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfilenew.h \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfileopen.h \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfilepdf.h \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfilesvg.h \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfileprint.h \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfileprintpreview.h \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfilequit.h \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfilesaveas.h \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfilesave.h \
    ../../thrd/qcad2/qcadactions/src/info/rs_actioninfoangle.h \
    ../../thrd/qcad2/qcadactions/src/info/rs_actioninfoarea.h \
    ../../thrd/qcad2/qcadactions/src/info/rs_actioninfodist2.h \
    ../../thrd/qcad2/qcadactions/src/info/rs_actioninfodist.h \
    ../../thrd/qcad2/qcadactions/src/info/rs_actioninfoinside.h \
    ../../thrd/qcad2/qcadactions/src/info/rs_actioninfototallength.h \
    ../../thrd/qcad2/qcadactions/src/layers/rs_actionlayersadd.h \
    ../../thrd/qcad2/qcadactions/src/layers/rs_actionlayersduplicate.h \
    ../../thrd/qcad2/qcadactions/src/layers/rs_actionlayersedit.h \
    ../../thrd/qcad2/qcadactions/src/layers/rs_actionlayershideall.h \
    ../../thrd/qcad2/qcadactions/src/layers/rs_actionlayersremove.h \
    ../../thrd/qcad2/qcadactions/src/layers/rs_actionlayersshowall.h \
    ../../thrd/qcad2/qcadactions/src/layers/rs_actionlayerstogglelock.h \
    ../../thrd/qcad2/qcadactions/src/layers/rs_actionlayerstoggleview.h \
    ../../thrd/qcad2/qcadactions/src/misc/rs_actionback.h \
    ../../thrd/qcad2/qcadactions/src/misc/rs_actionbase.h \
    ../../thrd/qcad2/qcadactions/src/misc/rs_actiondefault.h \
    ../../thrd/qcad2/qcadactions/src/misc/rs_actionforward.h \
    ../../thrd/qcad2/qcadactions/src/misc/rs_actionlibraryinsert.h \
    ../../thrd/qcad2/qcadactions/src/misc/rs_actionparisdebugcreatecontainer.h \
    ../../thrd/qcad2/qcadactions/src/misc/rs_actionreset.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyattributes.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifybevel.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifydeletefree.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifydelete.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifydeletequick.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifydivide2.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifydivide.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyentity.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifytext.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyexplode.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyexplodetext.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyisoproject.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifymirror.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifymove.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifymoverotate.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyrotate2.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyrotate.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyround.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyscale.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifystretch.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifytoback.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifytofront.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifytrimamount.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifytrim.h \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifytrimboth.h \
    ../../thrd/qcad2/qcadactions/src/options/rs_actionoptionsdrawing.h \
    ../../thrd/qcad2/qcadactions/src/options/rs_actionoptionsgeneral.h \
    ../../thrd/qcad2/qcadactions/src/script/rs_actionscriptopenide.h \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectall.h \
    ../../thrd/qcad2/qcadactions/src/select/rs_actiondeselectall.h \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectbase.h \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectcurrentlayer.h \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectcontour.h \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselect.h \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectintersected.h \
    ../../thrd/qcad2/qcadactions/src/select/rs_actiondeselectintersected.h \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectinvert.h \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectlayer.h \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectsingle.h \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectwindow.h \
    ../../thrd/qcad2/qcadactions/src/select/rs_actiondeselectwindow.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionlockrelativezero.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetrelativezero.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmode.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodeauto.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodefree.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodegrid.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodeendpoint.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodeonentity.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodecenter.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodemiddle.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodedist.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodeintersection.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodereference.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodecoordinate.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodecoordinatepolar.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnaprestriction.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnaprestrictionnothing.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnaprestrictionorthogonal.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnaprestrictionhorizontal.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnaprestrictionvertical.h \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsnapintersectionmanual.h \
    ../../thrd/qcad2/qcadactions/src/view/rs_actionviewdraft.h \
    ../../thrd/qcad2/qcadactions/src/view/rs_actionviewgrid.h \
    ../../thrd/qcad2/qcadactions/src/view/rs_actionviewstatusbar.h \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomauto.h \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomautoy.h \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomin.h \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomout.h \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoompan.h \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomprevious.h \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomredraw.h \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomselection.h \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomscroll.h \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomwindow.h

SOURCES = \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblocksadd.cpp \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblocksattributes.cpp \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblockscreate.cpp \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblocksedit.cpp \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblockseditinsert.cpp \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblocksinsert.cpp \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblocksremove.cpp \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblockstoggleview.cpp \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblocksshowall.cpp \
    ../../thrd/qcad2/qcadactions/src/blocks/rs_actionblockshideall.cpp \
    ../../thrd/qcad2/qcadactions/src/debugging/rs_actiondebugentities.cpp \
    ../../thrd/qcad2/qcadactions/src/debugging/rs_actiondebugguiactions.cpp \
    ../../thrd/qcad2/qcadactions/src/debugging/rs_actiondebugresize.cpp \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimaligned.cpp \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimangular.cpp \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimdiametric.cpp \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimension.cpp \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimleader.cpp \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimlinear.cpp \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimradial.cpp \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimordinate.cpp \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimhorizontal.cpp \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiondimvertical.cpp \
    ../../thrd/qcad2/qcadactions/src/dimension/rs_actiontoolregeneratedimensions.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawarc3p.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawarc.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawarctangential.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawcircle2p.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawcircle3p.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawcircle.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawcirclecr.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawellipsearcaxis.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawellipseaxis.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawhatch.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawimage.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlineangle.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinebisector.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawline.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinefree.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodegrid.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodeendpoint.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodeonentity.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodecenter.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodemiddle.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodedist.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodeintersection.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodereference.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodecoordinate.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodecoordinatepolar.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinehorizontal.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinehorvert.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlineparallel.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawarcparallel.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawcircleparallel.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlineparallelthrough.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinepolygon2.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinepolygon.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinerectangle.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinerelangle.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinetangent1.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinetangent2.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlinevertical.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawlineorthogonal.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawpoint.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawpolyline.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawspline.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actiondrawtext.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actionpolylineadd.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actionpolylineappend.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actionpolylinedel.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actionpolylinedelbetween.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actionpolylineequidistant.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actionpolylinefromsegments.cpp \
    ../../thrd/qcad2/qcadactions/src/draw/rs_actionpolylinetrim.cpp \
    ../../thrd/qcad2/qcadactions/src/edit/rs_actioneditcopy.cpp \
    ../../thrd/qcad2/qcadactions/src/edit/rs_actioneditcopyautoref.cpp \
    ../../thrd/qcad2/qcadactions/src/edit/rs_actioneditcut.cpp \
    ../../thrd/qcad2/qcadactions/src/edit/rs_actioneditcutautoref.cpp \
    ../../thrd/qcad2/qcadactions/src/edit/rs_actioneditpaste.cpp \
    ../../thrd/qcad2/qcadactions/src/edit/rs_actioneditundo.cpp \
    ../../thrd/qcad2/qcadactions/src/edit/rs_actioneditredo.cpp \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfileclose.cpp \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfileexport.cpp \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfilenew.cpp \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfileopen.cpp \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfilepdf.cpp \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfilesvg.cpp \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfileprint.cpp \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfileprintpreview.cpp \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfilequit.cpp \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfilesaveas.cpp \
    ../../thrd/qcad2/qcadactions/src/file/rs_actionfilesave.cpp \
    ../../thrd/qcad2/qcadactions/src/info/rs_actioninfoangle.cpp \
    ../../thrd/qcad2/qcadactions/src/info/rs_actioninfoarea.cpp \
    ../../thrd/qcad2/qcadactions/src/info/rs_actioninfodist2.cpp \
    ../../thrd/qcad2/qcadactions/src/info/rs_actioninfodist.cpp \
    ../../thrd/qcad2/qcadactions/src/info/rs_actioninfoinside.cpp \
    ../../thrd/qcad2/qcadactions/src/info/rs_actioninfototallength.cpp \
    ../../thrd/qcad2/qcadactions/src/layers/rs_actionlayersadd.cpp \
    ../../thrd/qcad2/qcadactions/src/layers/rs_actionlayersduplicate.cpp \
    ../../thrd/qcad2/qcadactions/src/layers/rs_actionlayersedit.cpp \
    ../../thrd/qcad2/qcadactions/src/layers/rs_actionlayershideall.cpp \
    ../../thrd/qcad2/qcadactions/src/layers/rs_actionlayersremove.cpp \
    ../../thrd/qcad2/qcadactions/src/layers/rs_actionlayersshowall.cpp \
    ../../thrd/qcad2/qcadactions/src/layers/rs_actionlayerstogglelock.cpp \
    ../../thrd/qcad2/qcadactions/src/layers/rs_actionlayerstoggleview.cpp \
    ../../thrd/qcad2/qcadactions/src/misc/rs_actionback.cpp \
    ../../thrd/qcad2/qcadactions/src/misc/rs_actiondefault.cpp \
    ../../thrd/qcad2/qcadactions/src/misc/rs_actionforward.cpp \
    ../../thrd/qcad2/qcadactions/src/misc/rs_actionlibraryinsert.cpp \
    ../../thrd/qcad2/qcadactions/src/misc/rs_actionparisdebugcreatecontainer.cpp \
    ../../thrd/qcad2/qcadactions/src/misc/rs_actionreset.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyattributes.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifybevel.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifydelete.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifydeletefree.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifydeletequick.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifydivide2.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifydivide.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyentity.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifytext.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyexplode.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyexplodetext.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyisoproject.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifymirror.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifymove.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifymoverotate.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyrotate2.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyrotate.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyround.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifyscale.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifystretch.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifytoback.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifytofront.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifytrimamount.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifytrim.cpp \
    ../../thrd/qcad2/qcadactions/src/modify/rs_actionmodifytrimboth.cpp \
    ../../thrd/qcad2/qcadactions/src/options/rs_actionoptionsdrawing.cpp \
    ../../thrd/qcad2/qcadactions/src/options/rs_actionoptionsgeneral.cpp \
    ../../thrd/qcad2/qcadactions/src/script/rs_actionscriptopenide.cpp \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectall.cpp \
    ../../thrd/qcad2/qcadactions/src/select/rs_actiondeselectall.cpp \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectbase.cpp \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectcurrentlayer.cpp \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectcontour.cpp \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselect.cpp \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectintersected.cpp \
    ../../thrd/qcad2/qcadactions/src/select/rs_actiondeselectintersected.cpp \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectinvert.cpp \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectlayer.cpp \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectsingle.cpp \
    ../../thrd/qcad2/qcadactions/src/select/rs_actionselectwindow.cpp \
    ../../thrd/qcad2/qcadactions/src/select/rs_actiondeselectwindow.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionlockrelativezero.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetrelativezero.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmode.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodeauto.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnapmodefree.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnaprestriction.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnaprestrictionnothing.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnaprestrictionorthogonal.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnaprestrictionhorizontal.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsetsnaprestrictionvertical.cpp \
    ../../thrd/qcad2/qcadactions/src/snap/rs_actionsnapintersectionmanual.cpp \
    ../../thrd/qcad2/qcadactions/src/view/rs_actionviewdraft.cpp \
    ../../thrd/qcad2/qcadactions/src/view/rs_actionviewgrid.cpp \
    ../../thrd/qcad2/qcadactions/src/view/rs_actionviewstatusbar.cpp \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomauto.cpp \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomautoy.cpp \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomin.cpp \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomout.cpp \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoompan.cpp \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomprevious.cpp \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomredraw.cpp \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomselection.cpp \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomscroll.cpp \
    ../../thrd/qcad2/qcadactions/src/zoom/rs_actionzoomwindow.cpp

# qcadguiqt
FORMS = \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_aboutdialog.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_blockdialog.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgarc.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgattributes.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgcircle.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgdimension.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgdimlinear.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgellipse.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlghatch.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgimageoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlginitial.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlginsert.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgline.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgmirror.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgmoverotate.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgmove.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgonetime.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgoptionsdrawing.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgoptionsgeneral.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgpoint.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgrotate2.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgrotate.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgscale.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgspline.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_dlgtext.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_exitdialog.ui \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/ui/qg_layerdialog.ui \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/ui/qg_cadtoolbararcs.ui \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/ui/qg_cadtoolbarcircles.ui \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/ui/qg_cadtoolbardim.ui \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/ui/qg_cadtoolbarellipses.ui \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/ui/qg_cadtoolbarinfo.ui \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/ui/qg_cadtoolbarlines.ui \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/ui/qg_cadtoolbarmain.ui \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/ui/qg_cadtoolbarmodify.ui \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/ui/qg_cadtoolbarpoints.ui \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/ui/qg_cadtoolbarselect.ui \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/ui/qg_cadtoolbarsnap.ui \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/ui/qg_cadtoolbarsplines.ui \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/ui/qg_cadtoolbar.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_arcoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_arctangentialoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_beveloptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_circleoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_divide2options.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_dimlinearoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_dimoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_editpasteoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_imageoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_insertoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_isoprojectoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_libraryinsertoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_lineangleoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_linebisectoroptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_lineoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_lineparalleloptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_lineparallelthroughoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_linepolygon2options.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_linepolygonoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_linerelangleoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_moverotateoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_printpreviewoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_roundoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_snapcoordinateoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_snapcoordinatepolaroptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_snapdistoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_splineoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_textoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_trimamountoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/widgets/ui/qg_coordinatewidget.ui \
    ../../thrd/qcad2/qcadguiqt/src/widgets/ui/qg_librarywidget.ui \
    ../../thrd/qcad2/qcadguiqt/src/widgets/ui/qg_mousewidget.ui \
    ../../thrd/qcad2/qcadguiqt/src/widgets/ui/qg_selectionwidget.ui \
    ../../thrd/qcad2/qcadguiqt/src/widgets/ui/qg_widgetdimensionlabel.ui \
    ../../thrd/qcad2/qcadguiqt/src/widgets/ui/qg_widgetpen.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_polylineoptions.ui \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/ui/qg_cadtoolbarpolylines.ui \
    ../../thrd/qcad2/qcadguiqt/src/widgets/ui/qg_commandwidget.ui \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/ui/qg_polylineequidistantoptions.ui
	
HEADERS = \
    ../../thrd/qcad2/qcadguiqt/src/qg_dialogfactory.h \
    ../../thrd/qcad2/qcadguiqt/src/qg_graphicview.h \
    ../../thrd/qcad2/qcadguiqt/src/qg_mainwindow.h \
    ../../thrd/qcad2/qcadguiqt/src/qg_mdiwindow.h \
    ../../thrd/qcad2/qcadguiqt/src/qg_recentfiles.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_aboutdialog.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_blockdialog.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgarc.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgattributes.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgcircle.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgdimension.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgdimlinear.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgellipse.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlghatch.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgimageoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlginitial.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlginsert.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgline.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgmirror.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgmove.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgmoverotate.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgonetime.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgoptionsdrawing.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgoptionsgeneral.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgpoint.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgrotate2.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgrotate.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgscale.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgspline.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgtext.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_exitdialog.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_filedialog.h \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_layerdialog.h \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbararcs.h \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarbase.h \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarcircles.h \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbardim.h \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarellipses.h \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbar.h \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarinfo.h \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarlines.h \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarmain.h \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarmodify.h \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarpoints.h \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarselect.h \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarsnap.h \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarsplines.h \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_pentoolbar.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_arcoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_arctangentialoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_beveloptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_circleoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_divide2options.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_dimlinearoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_dimoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_editpasteoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_imageoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_insertoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_isoprojectoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_libraryinsertoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_lineangleoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_linebisectoroptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_lineoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_lineparalleloptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_lineparallelthroughoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_linepolygon2options.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_linepolygonoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_linerelangleoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_moverotateoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_optionsbase.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_printpreviewoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_roundoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_snapcoordinateoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_snapcoordinatepolaroptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_snapdistoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_snapoptionsbase.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_splineoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_textoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_trimamountoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_blockwidget.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_colorbox.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_coordinatewidget.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_fontbox.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_layerbox.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_layerwidget.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_librarywidget.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_linetypebox.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_listwidget.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_mousewidget.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_patternbox.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_ruler.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_scrollbar.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_selectionwidget.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_tablewidget.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_widgetdimensionlabel.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_widgetpen.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_widthbox.h \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarpolylines.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_commandedit.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_commandwidget.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_polylineequidistantoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_polylineoptions.h \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_propertyeditor.h
	
SOURCES = \
    ../../thrd/qcad2/qcadguiqt/src/qg_mdiwindow.cpp \
    ../../thrd/qcad2/qcadguiqt/src/qg_dialogfactory.cpp \
    ../../thrd/qcad2/qcadguiqt/src/qg_graphicview.cpp \
    ../../thrd/qcad2/qcadguiqt/src/qg_mainwindow.cpp \
    ../../thrd/qcad2/qcadguiqt/src/qg_recentfiles.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_aboutdialog.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgscale.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_exitdialog.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlginsert.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgspline.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlghatch.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgtext.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgoptionsdrawing.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_blockdialog.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgarc.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgmove.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_layerdialog.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgellipse.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgdimension.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgmirror.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgdimlinear.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlginitial.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_filedialog.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgimageoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgpoint.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgline.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgcircle.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgattributes.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgrotate2.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgoptionsgeneral.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgmoverotate.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgonetime.cpp \
    ../../thrd/qcad2/qcadguiqt/src/dialogs/qg_dlgrotate.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_splineoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_arctangentialoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_insertoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_snapcoordinateoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_lineoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_dimoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_printpreviewoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_libraryinsertoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_circleoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_isoprojectoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_lineangleoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_lineparalleloptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_linepolygon2options.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_roundoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_snapdistoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_linebisectoroptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_moverotateoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_linerelangleoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_imageoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_dimlinearoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_textoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_trimamountoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_linepolygonoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_editpasteoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_lineparallelthroughoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_beveloptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_divide2options.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_snapcoordinatepolaroptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_arcoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_pentoolbar.cpp \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarmain.cpp \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarsplines.cpp \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarlines.cpp \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarcircles.cpp \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbar.cpp \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarpoints.cpp \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbararcs.cpp \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbardim.cpp \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarinfo.cpp \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarsnap.cpp \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarmodify.cpp \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarbase.cpp \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarselect.cpp \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarellipses.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_blockwidget.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_colorbox.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_coordinatewidget.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_fontbox.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_layerbox.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_layerwidget.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_librarywidget.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_linetypebox.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_listwidget.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_mousewidget.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_patternbox.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_ruler.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_selectionwidget.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_tablewidget.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_widgetdimensionlabel.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_widgetpen.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_widthbox.cpp \
    ../../thrd/qcad2/qcadguiqt/src/toolbars/qg_cadtoolbarpolylines.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_commandedit.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_commandwidget.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_polylineequidistantoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/tooloptions/qg_polylineoptions.cpp \
    ../../thrd/qcad2/qcadguiqt/src/widgets/qg_propertyeditor.cpp






	
	
RESOURCES = \
    ../../thrd/qcad2/qcadactions/src/qcadactions.qrc \
    ../../thrd/qcad2/qcadguiqt/src/qcadguiqt.qrc


OTHER_FILES = \

#    ../src/gui/db_browserdialog.dox \
