TEMPLATE    = lib
DESTDIR     = lib
CONFIG      += qt staticlib warn_on

exists( ../mkspecs/defs.pro ) {
    include( ../mkspecs/defs.pro )
}

INCLUDEPATH += \
    ./src \
    ./src/dialogs \
    ./src/toolbars \
    ./src/tooloptions \
    ./src/widgets \
    ../dxflib/src \
    ../qcadlib/src \
    ../qcadlib/src/actions \
    ../qcadlib/src/creation \
    ../qcadlib/src/debug \
    ../qcadlib/src/entities \
    ../qcadlib/src/fileio \
    ../qcadlib/src/filters \
    ../qcadlib/src/global \
    ../qcadlib/src/gui \
    ../qcadlib/src/information \
    ../qcadlib/src/math \
    ../qcadlib/src/modification \
    ../qcadlib/src/scripting \
    ../qcadlib/src/tools \
    ../qcadactions/src \
    ../qcadactions/src/blocks \
    ../qcadactions/src/debugging \
    ../qcadactions/src/dimension \
    ../qcadactions/src/draw \
    ../qcadactions/src/edit \
    ../qcadactions/src/file \
    ../qcadactions/src/info \
    ../qcadactions/src/layers \
    ../qcadactions/src/misc \
    ../qcadactions/src/modify \
    ../qcadactions/src/select \
    ../qcadactions/src/snap \
    ../qcadactions/src/view \
    ../qcadactions/src/zoom \
    ../rwbearch/src/actions \
    ../rwbearch/src/entities \
    ../rwbearch/src/filters \
    ../rwbearch/src/tools \
    ../rwbearch/src/wrappers \
    ../fparser/src \
    ../qcadguiqt/src

FORMS = \
    ./src/dialogs/ui/qg_aboutdialog.ui \
    ./src/dialogs/ui/qg_blockdialog.ui \
    ./src/dialogs/ui/qg_dlgarc.ui \
    ./src/dialogs/ui/qg_dlgattributes.ui \
    ./src/dialogs/ui/qg_dlgcircle.ui \
    ./src/dialogs/ui/qg_dlgdimension.ui \
    ./src/dialogs/ui/qg_dlgdimlinear.ui \
    ./src/dialogs/ui/qg_dlgellipse.ui \
    ./src/dialogs/ui/qg_dlghatch.ui \
    ./src/dialogs/ui/qg_dlgimageoptions.ui \
    ./src/dialogs/ui/qg_dlginitial.ui \
    ./src/dialogs/ui/qg_dlginsert.ui \
    ./src/dialogs/ui/qg_dlgline.ui \
    ./src/dialogs/ui/qg_dlgmirror.ui \
    ./src/dialogs/ui/qg_dlgmoverotate.ui \
    ./src/dialogs/ui/qg_dlgmove.ui \
    ./src/dialogs/ui/qg_dlgonetime.ui \
    ./src/dialogs/ui/qg_dlgoptionsdrawing.ui \
    ./src/dialogs/ui/qg_dlgoptionsgeneral.ui \
    ./src/dialogs/ui/qg_dlgpoint.ui \
    ./src/dialogs/ui/qg_dlgrotate2.ui \
    ./src/dialogs/ui/qg_dlgrotate.ui \
    ./src/dialogs/ui/qg_dlgscale.ui \
    ./src/dialogs/ui/qg_dlgspline.ui \
    ./src/dialogs/ui/qg_dlgtext.ui \
    ./src/dialogs/ui/qg_exitdialog.ui \
    ./src/dialogs/ui/qg_layerdialog.ui \
    ./src/toolbars/ui/qg_cadtoolbararcs.ui \
    ./src/toolbars/ui/qg_cadtoolbarcircles.ui \
    ./src/toolbars/ui/qg_cadtoolbardim.ui \
    ./src/toolbars/ui/qg_cadtoolbarellipses.ui \
    ./src/toolbars/ui/qg_cadtoolbarinfo.ui \
    ./src/toolbars/ui/qg_cadtoolbarlines.ui \
    ./src/toolbars/ui/qg_cadtoolbarmain.ui \
    ./src/toolbars/ui/qg_cadtoolbarmodify.ui \
    ./src/toolbars/ui/qg_cadtoolbarpoints.ui \
    ./src/toolbars/ui/qg_cadtoolbarselect.ui \
    ./src/toolbars/ui/qg_cadtoolbarsnap.ui \
    ./src/toolbars/ui/qg_cadtoolbarsplines.ui \
    ./src/toolbars/ui/qg_cadtoolbar.ui \
    ./src/tooloptions/ui/qg_arcoptions.ui \
    ./src/tooloptions/ui/qg_arctangentialoptions.ui \
    ./src/tooloptions/ui/qg_beveloptions.ui \
    ./src/tooloptions/ui/qg_circleoptions.ui \
    ./src/tooloptions/ui/qg_divide2options.ui \
    ./src/tooloptions/ui/qg_dimlinearoptions.ui \
    ./src/tooloptions/ui/qg_dimoptions.ui \
    ./src/tooloptions/ui/qg_editpasteoptions.ui \
    ./src/tooloptions/ui/qg_imageoptions.ui \
    ./src/tooloptions/ui/qg_insertoptions.ui \
    ./src/tooloptions/ui/qg_isoprojectoptions.ui \
    ./src/tooloptions/ui/qg_libraryinsertoptions.ui \
    ./src/tooloptions/ui/qg_lineangleoptions.ui \
    ./src/tooloptions/ui/qg_linebisectoroptions.ui \
    ./src/tooloptions/ui/qg_lineoptions.ui \
    ./src/tooloptions/ui/qg_lineparalleloptions.ui \
    ./src/tooloptions/ui/qg_lineparallelthroughoptions.ui \
    ./src/tooloptions/ui/qg_linepolygon2options.ui \
    ./src/tooloptions/ui/qg_linepolygonoptions.ui \
    ./src/tooloptions/ui/qg_linerelangleoptions.ui \
    ./src/tooloptions/ui/qg_moverotateoptions.ui \
    ./src/tooloptions/ui/qg_printpreviewoptions.ui \
    ./src/tooloptions/ui/qg_roundoptions.ui \
    ./src/tooloptions/ui/qg_snapcoordinateoptions.ui \
    ./src/tooloptions/ui/qg_snapcoordinatepolaroptions.ui \
    ./src/tooloptions/ui/qg_snapdistoptions.ui \
    ./src/tooloptions/ui/qg_splineoptions.ui \
    ./src/tooloptions/ui/qg_textoptions.ui \
    ./src/tooloptions/ui/qg_trimamountoptions.ui \
    ./src/widgets/ui/qg_coordinatewidget.ui \
    ./src/widgets/ui/qg_librarywidget.ui \
    ./src/widgets/ui/qg_mousewidget.ui \
    ./src/widgets/ui/qg_selectionwidget.ui \
    ./src/widgets/ui/qg_widgetdimensionlabel.ui \
    ./src/widgets/ui/qg_widgetpen.ui \
    ./src/tooloptions/ui/qg_polylineoptions.ui \
    ./src/toolbars/ui/qg_cadtoolbarpolylines.ui \
    ./src/widgets/ui/qg_commandwidget.ui \
    ./src/tooloptions/ui/qg_polylineequidistantoptions.ui
HEADERS = \
    ./src/qg_dialogfactory.h \
    ./src/qg_graphicview.h \
    ./src/qg_mainwindow.h \
    ./src/qg_mdiwindow.h \
    ./src/qg_recentfiles.h \
    ./src/dialogs/qg_aboutdialog.h \
    ./src/dialogs/qg_blockdialog.h \
    ./src/dialogs/qg_dlgarc.h \
    ./src/dialogs/qg_dlgattributes.h \
    ./src/dialogs/qg_dlgcircle.h \
    ./src/dialogs/qg_dlgdimension.h \
    ./src/dialogs/qg_dlgdimlinear.h \
    ./src/dialogs/qg_dlgellipse.h \
    ./src/dialogs/qg_dlghatch.h \
    ./src/dialogs/qg_dlgimageoptions.h \
    ./src/dialogs/qg_dlginitial.h \
    ./src/dialogs/qg_dlginsert.h \
    ./src/dialogs/qg_dlgline.h \
    ./src/dialogs/qg_dlgmirror.h \
    ./src/dialogs/qg_dlgmove.h \
    ./src/dialogs/qg_dlgmoverotate.h \
    ./src/dialogs/qg_dlgonetime.h \
    ./src/dialogs/qg_dlgoptionsdrawing.h \
    ./src/dialogs/qg_dlgoptionsgeneral.h \
    ./src/dialogs/qg_dlgpoint.h \
    ./src/dialogs/qg_dlgrotate2.h \
    ./src/dialogs/qg_dlgrotate.h \
    ./src/dialogs/qg_dlgscale.h \
    ./src/dialogs/qg_dlgspline.h \
    ./src/dialogs/qg_dlgtext.h \
    ./src/dialogs/qg_exitdialog.h \
    ./src/dialogs/qg_filedialog.h \
    ./src/dialogs/qg_layerdialog.h \
    ./src/toolbars/qg_cadtoolbararcs.h \
    ./src/toolbars/qg_cadtoolbarbase.h \
    ./src/toolbars/qg_cadtoolbarcircles.h \
    ./src/toolbars/qg_cadtoolbardim.h \
    ./src/toolbars/qg_cadtoolbarellipses.h \
    ./src/toolbars/qg_cadtoolbar.h \
    ./src/toolbars/qg_cadtoolbarinfo.h \
    ./src/toolbars/qg_cadtoolbarlines.h \
    ./src/toolbars/qg_cadtoolbarmain.h \
    ./src/toolbars/qg_cadtoolbarmodify.h \
    ./src/toolbars/qg_cadtoolbarpoints.h \
    ./src/toolbars/qg_cadtoolbarselect.h \
    ./src/toolbars/qg_cadtoolbarsnap.h \
    ./src/toolbars/qg_cadtoolbarsplines.h \
    ./src/toolbars/qg_pentoolbar.h \
    ./src/tooloptions/qg_arcoptions.h \
    ./src/tooloptions/qg_arctangentialoptions.h \
    ./src/tooloptions/qg_beveloptions.h \
    ./src/tooloptions/qg_circleoptions.h \
    ./src/tooloptions/qg_divide2options.h \
    ./src/tooloptions/qg_dimlinearoptions.h \
    ./src/tooloptions/qg_dimoptions.h \
    ./src/tooloptions/qg_editpasteoptions.h \
    ./src/tooloptions/qg_imageoptions.h \
    ./src/tooloptions/qg_insertoptions.h \
    ./src/tooloptions/qg_isoprojectoptions.h \
    ./src/tooloptions/qg_libraryinsertoptions.h \
    ./src/tooloptions/qg_lineangleoptions.h \
    ./src/tooloptions/qg_linebisectoroptions.h \
    ./src/tooloptions/qg_lineoptions.h \
    ./src/tooloptions/qg_lineparalleloptions.h \
    ./src/tooloptions/qg_lineparallelthroughoptions.h \
    ./src/tooloptions/qg_linepolygon2options.h \
    ./src/tooloptions/qg_linepolygonoptions.h \
    ./src/tooloptions/qg_linerelangleoptions.h \
    ./src/tooloptions/qg_moverotateoptions.h \
    ./src/tooloptions/qg_optionsbase.h \
    ./src/tooloptions/qg_printpreviewoptions.h \
    ./src/tooloptions/qg_roundoptions.h \
    ./src/tooloptions/qg_snapcoordinateoptions.h \
    ./src/tooloptions/qg_snapcoordinatepolaroptions.h \
    ./src/tooloptions/qg_snapdistoptions.h \
    ./src/tooloptions/qg_snapoptionsbase.h \
    ./src/tooloptions/qg_splineoptions.h \
    ./src/tooloptions/qg_textoptions.h \
    ./src/tooloptions/qg_trimamountoptions.h \
    ./src/widgets/qg_blockwidget.h \
    ./src/widgets/qg_colorbox.h \
    ./src/widgets/qg_coordinatewidget.h \
    ./src/widgets/qg_fontbox.h \
    ./src/widgets/qg_layerbox.h \
    ./src/widgets/qg_layerwidget.h \
    ./src/widgets/qg_librarywidget.h \
    ./src/widgets/qg_linetypebox.h \
    ./src/widgets/qg_listwidget.h \
    ./src/widgets/qg_mousewidget.h \
    ./src/widgets/qg_patternbox.h \
    ./src/widgets/qg_ruler.h \
    ./src/widgets/qg_scrollbar.h \
    ./src/widgets/qg_selectionwidget.h \
    ./src/widgets/qg_tablewidget.h \
    ./src/widgets/qg_widgetdimensionlabel.h \
    ./src/widgets/qg_widgetpen.h \
    ./src/widgets/qg_widthbox.h \
    ./src/toolbars/qg_cadtoolbarpolylines.h \
    ./src/widgets/qg_commandedit.h \
    ./src/widgets/qg_commandwidget.h \
    ./src/tooloptions/qg_polylineequidistantoptions.h \
    ./src/tooloptions/qg_polylineoptions.h \
    ./src/widgets/qg_propertyeditor.h
SOURCES = \
    ./src/qg_mdiwindow.cpp \
    ./src/qg_dialogfactory.cpp \
    ./src/qg_graphicview.cpp \
    ./src/qg_mainwindow.cpp \
    ./src/qg_recentfiles.cpp \
    ./src/dialogs/qg_aboutdialog.cpp \
    ./src/dialogs/qg_dlgscale.cpp \
    ./src/dialogs/qg_exitdialog.cpp \
    ./src/dialogs/qg_dlginsert.cpp \
    ./src/dialogs/qg_dlgspline.cpp \
    ./src/dialogs/qg_dlghatch.cpp \
    ./src/dialogs/qg_dlgtext.cpp \
    ./src/dialogs/qg_dlgoptionsdrawing.cpp \
    ./src/dialogs/qg_blockdialog.cpp \
    ./src/dialogs/qg_dlgarc.cpp \
    ./src/dialogs/qg_dlgmove.cpp \
    ./src/dialogs/qg_layerdialog.cpp \
    ./src/dialogs/qg_dlgellipse.cpp \
    ./src/dialogs/qg_dlgdimension.cpp \
    ./src/dialogs/qg_dlgmirror.cpp \
    ./src/dialogs/qg_dlgdimlinear.cpp \
    ./src/dialogs/qg_dlginitial.cpp \
    ./src/dialogs/qg_filedialog.cpp \
    ./src/dialogs/qg_dlgimageoptions.cpp \
    ./src/dialogs/qg_dlgpoint.cpp \
    ./src/dialogs/qg_dlgline.cpp \
    ./src/dialogs/qg_dlgcircle.cpp \
    ./src/dialogs/qg_dlgattributes.cpp \
    ./src/dialogs/qg_dlgrotate2.cpp \
    ./src/dialogs/qg_dlgoptionsgeneral.cpp \
    ./src/dialogs/qg_dlgmoverotate.cpp \
    ./src/dialogs/qg_dlgonetime.cpp \
    ./src/dialogs/qg_dlgrotate.cpp \
    ./src/tooloptions/qg_splineoptions.cpp \
    ./src/tooloptions/qg_arctangentialoptions.cpp \
    ./src/tooloptions/qg_insertoptions.cpp \
    ./src/tooloptions/qg_snapcoordinateoptions.cpp \
    ./src/tooloptions/qg_lineoptions.cpp \
    ./src/tooloptions/qg_dimoptions.cpp \
    ./src/tooloptions/qg_printpreviewoptions.cpp \
    ./src/tooloptions/qg_libraryinsertoptions.cpp \
    ./src/tooloptions/qg_circleoptions.cpp \
    ./src/tooloptions/qg_isoprojectoptions.cpp \
    ./src/tooloptions/qg_lineangleoptions.cpp \
    ./src/tooloptions/qg_lineparalleloptions.cpp \
    ./src/tooloptions/qg_linepolygon2options.cpp \
    ./src/tooloptions/qg_roundoptions.cpp \
    ./src/tooloptions/qg_snapdistoptions.cpp \
    ./src/tooloptions/qg_linebisectoroptions.cpp \
    ./src/tooloptions/qg_moverotateoptions.cpp \
    ./src/tooloptions/qg_linerelangleoptions.cpp \
    ./src/tooloptions/qg_imageoptions.cpp \
    ./src/tooloptions/qg_dimlinearoptions.cpp \
    ./src/tooloptions/qg_textoptions.cpp \
    ./src/tooloptions/qg_trimamountoptions.cpp \
    ./src/tooloptions/qg_linepolygonoptions.cpp \
    ./src/tooloptions/qg_editpasteoptions.cpp \
    ./src/tooloptions/qg_lineparallelthroughoptions.cpp \
    ./src/tooloptions/qg_beveloptions.cpp \
    ./src/tooloptions/qg_divide2options.cpp \
    ./src/tooloptions/qg_snapcoordinatepolaroptions.cpp \
    ./src/tooloptions/qg_arcoptions.cpp \
    ./src/toolbars/qg_pentoolbar.cpp \
    ./src/toolbars/qg_cadtoolbarmain.cpp \
    ./src/toolbars/qg_cadtoolbarsplines.cpp \
    ./src/toolbars/qg_cadtoolbarlines.cpp \
    ./src/toolbars/qg_cadtoolbarcircles.cpp \
    ./src/toolbars/qg_cadtoolbar.cpp \
    ./src/toolbars/qg_cadtoolbarpoints.cpp \
    ./src/toolbars/qg_cadtoolbararcs.cpp \
    ./src/toolbars/qg_cadtoolbardim.cpp \
    ./src/toolbars/qg_cadtoolbarinfo.cpp \
    ./src/toolbars/qg_cadtoolbarsnap.cpp \
    ./src/toolbars/qg_cadtoolbarmodify.cpp \
    ./src/toolbars/qg_cadtoolbarbase.cpp \
    ./src/toolbars/qg_cadtoolbarselect.cpp \
    ./src/toolbars/qg_cadtoolbarellipses.cpp \
    ./src/widgets/qg_blockwidget.cpp \
    ./src/widgets/qg_colorbox.cpp \
    ./src/widgets/qg_coordinatewidget.cpp \
    ./src/widgets/qg_fontbox.cpp \
    ./src/widgets/qg_layerbox.cpp \
    ./src/widgets/qg_layerwidget.cpp \
    ./src/widgets/qg_librarywidget.cpp \
    ./src/widgets/qg_linetypebox.cpp \
    ./src/widgets/qg_listwidget.cpp \
    ./src/widgets/qg_mousewidget.cpp \
    ./src/widgets/qg_patternbox.cpp \
    ./src/widgets/qg_ruler.cpp \
    ./src/widgets/qg_selectionwidget.cpp \
    ./src/widgets/qg_tablewidget.cpp \
    ./src/widgets/qg_widgetdimensionlabel.cpp \
    ./src/widgets/qg_widgetpen.cpp \
    ./src/widgets/qg_widthbox.cpp \
    ./src/toolbars/qg_cadtoolbarpolylines.cpp \
    ./src/widgets/qg_commandedit.cpp \
    ./src/widgets/qg_commandwidget.cpp \
    ./src/tooloptions/qg_polylineequidistantoptions.cpp \
    ./src/tooloptions/qg_polylineoptions.cpp \
    ./src/widgets/qg_propertyeditor.cpp
TRANSLATIONS = \
    ./src/ts/qcadguiqt_bg.ts \
    ./src/ts/qcadguiqt_cs.ts \
    ./src/ts/qcadguiqt_cy.ts \
    ./src/ts/qcadguiqt_et.ts \
    ./src/ts/qcadguiqt_en.ts \
    ./src/ts/qcadguiqt_da.ts \
    ./src/ts/qcadguiqt_de.ts \
    ./src/ts/qcadguiqt_el.ts \
    ./src/ts/qcadguiqt_es.ts \
    ./src/ts/qcadguiqt_fr.ts \
    ./src/ts/qcadguiqt_hu.ts \
    ./src/ts/qcadguiqt_id.ts \
    ./src/ts/qcadguiqt_it.ts \
    ./src/ts/qcadguiqt_lt.ts \
    ./src/ts/qcadguiqt_ja.ts \
    ./src/ts/qcadguiqt_nl.ts \
    ./src/ts/qcadguiqt_no.ts \
    ./src/ts/qcadguiqt_pa.ts \
    ./src/ts/qcadguiqt_pl.ts \
    ./src/ts/qcadguiqt_pt.ts \
    ./src/ts/qcadguiqt_ru.ts \
    ./src/ts/qcadguiqt_sk.ts \
    ./src/ts/qcadguiqt_sv.ts \
    ./src/ts/qcadguiqt_tr.ts \
    ./src/ts/qcadguiqt_zh.ts

RESOURCES   = ./src/qcadguiqt.qrc

TARGET      = qcadguiqt

UI_DIR      = .ui
OBJECTS_DIR = .obj
MOC_DIR     = .moc
RCC_DIR     = .res


